services:
  integration-tests:
    image: integration-test
    build: .
    environment:
      WAIT_HOSTS: chrome:4444
      WAIT_TIMEOUT: 100
      INTEGRATION_TEST_BROWSER: "chrome"
      INTEGRATION_TEST_REMOTE: "true"
      INTEGRATION_TEST_REMOTE_URL: "http://chrome:4444"
      INTEGRATION_TEST_SLEEP_TIME: 5
  chrome:
    image: selenium-proxy
    build: selenium_proxy/
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      shm-size: "2g"
      LOCALHOST_PROXY_PORTS: ":8080 :5006 :9091 :5005"
    extra_hosts:
      - host.docker.internal:host-gateway
